baseURL = "https://fabschoolscat.netlify.app"
disableLanguages = []
disqusShortname = ""
googleAnalytics = "G-GN0NB9HJWR"
languageCode = "en-us"
languageName = "En"
paginate = "12"
summaryLength = "10"
theme = "twentytwenty"
title = "Fabschools"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "about"
name = "About"
weight = 3
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
description = "This is meta description"
[params.banner]
heading = "Announcing ‘Making Education Makers at Home’ Open Call Selected Projects"
image = "https://res.cloudinary.com/dbshcjrt3/image/upload/w_2400,h_760,c_fill,g_auto,q_auto/wikifactory-prod.uploads/420/inbound8412497604572328562_-_johnblaze_smith-5e65c.jpg"
[params.blog]
heading = "The Fabschools Catalog is Fablab Benfica Initiative. It is a Distributed Design Platform (Creative Europe) Activity. Some of the collected works were submitted by its authors or collected by the FLB Research Team."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = false
title = "Contact us for more information."
[params.cookies]
enable = true
expire_days = 2
[params.footer]
address = "Escola Superior de Educação de Lisboa<br>Campus de Benfica do IPL<br>1549-003 Lisboa"
content = "Fabschools is a set of activities of the Distributed Design Platform, run by IPL."
copyright = "cc-by 4.0 Fablab Benfica (Copyright &copy; 2020 a hugo theme by [themefisher])"
hours = ""
title = "Fabschools"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "fabschools@eselx.ipl.pt"
facebook = "https://www.facebook.com/FabLabBenfica/"
instagram = "https://www.instagram.com/fablab_benfica/"
linkedin = "https://www.linkedin.com/company/fablabbenfica/"
twitter = "https://twitter.com/BenficaFab"
yelp = ""
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
